### ISSUE TITLE
将ganler / overleaf_tongji_thesis迁移至TJ-CSCCG组织下

### ISSUE THREAD

**Issue by ganler** [TJ-CSCCG/overleaf_tongji_thesis#3]
## Why
- 因为本人即将毕业，之后本模板将失去维护，故想将其挂在一个org下，寻找新的维护人员。
- 本模板显然更适合放到有同济“商标”的组织架构下，而非个人项目；

## Call for maintainer:
- 根据反馈（e.g., issue）感谢latex内容；
- 定时上传overleaf（https://www.overleaf.com/latex/templates/tongji-undergrad-thesis/dfdvqsmpfcgk）
   - 请使用`tongji-undergrad-thesis`作为项目名称；
   - 请点击submit，提交到overleaf gallery，注意模板内的内容不得是具体一个人的毕设，否则管理员会退回；

在拥有maintainer之前&&2021年7月前，@ganler 会在TJ-CSCCG下继续维护该项目。

## Call for suggestions

@skyleaworlder
@E011011101001

所以如果你们觉得OK，就:
- [x] 把这个仓库删掉@skyleaworlder：https://github.com/TJ-CSCCG/overleaf_tongji_thesis 
- [x] 移交本仓库权限至TJ-CSCCG@ganler

**Comment by skyleaworlder** [comment]
我自然是觉得非常 OK。
我是这个仓库的 first star 嘛，从一开始就非常关注。

关于把仓库权限过渡到 TJ-CSCCG 下这件事，我觉得如果能这样自然是最好了。同意，我双手双脚资瓷！

**Comment by ganler** [comment]
@skyleaworlder sounds great. 那你先把我之前fork的这个仓库delete吧：https://github.com/TJ-CSCCG/overleaf_tongji_thesis
然后我migrate一下。

**Comment by skyleaworlder** [comment]
@ganler 抱歉回复晚了，finished!

**Comment by ganler** [comment]
Done. Thanks @skyleaworlder .
